<? PHP
/** * Простой и удобный чат-бот для bitrix24 */

$appsConfig = array();$configFileName = '/config_' . trim(str_replace('.', '_', $_REQUEST['auth']['domain'])) . '.php';if (file_exists(__DIR__ . $configFileName)) { include_once __DIR__ . $configFileName; }// получить событие "новое сообщение для бота"
if ($_REQUEST['event'] == 'ONIMBOTMESSAGEADD') { // проверить событие - зарегистрировать это приложение или нет
   если (! isset($appsConfig[$_REQUEST['auth']['application_token']])) { вернуть false; } // время отклика
   $arReport = getAnswer($_REQUEST['data']['PARAMS']['MESSAGE'], $_REQUEST['data']['PARAMS']['FROM_USER_ID']); $arReport['attach'][] = array("MESSAGE" => 'Как только вы закончите с этими задачами, просто спросите меня [отправить=что горячего]Что горячего?[ /отправить] еще раз - я дам вам больше, чтобы иметь на вашей тарелке!') ;  // отправить ответное сообщение
   $result = restCommand('imbot.message.add', массив ( "DIALOG_ID" => $_REQUEST['data']['PARAMS']['DIALOG_ID'], "СООБЩЕНИЕ" => $arReport['title'] . "\n" . $arReport['report'] . "\n", "ATTACH" => array_merge( $arReport['attach'] ), ), $_REQUEST["auth"]);  } // получить событие "открыть частный диалог с ботом" или "присоединиться к боту в групповой чат"
еще { if ($_REQUEST['event'] == 'ONIMBOTJOINCHAT') { // проверить событие - зарегистрировать это приложение или нет
      если (! isset($appsConfig[$_REQUEST['auth']['application_token']])) { вернуть false; } // отправьте справка по использованию чат-бота. Для приватного чата и группового чата необходимо отправить различные инструкции.
      $result = restCommand('imbot.message.add', array( 'DIALOG_ID' => $_REQUEST['data']['PARAMS']['DIALOG_ID'], 'СООБЩЕНИЕ' => Здравствуйте! Я Репорту, я могу быть болью в заднице, потому что я честен и откровенен". "ATTACH" => массив ( array('MESSAGE' => '[send=what's hot]What's hot?[ /отправить]'), ), ), $_REQUEST["auth"]);  } // получить событие "удалить чат-бота" еще { if ($_REQUEST['event'] == 'ONIMBOTDELETE') { // проверить событие - зарегистрировать это приложение или нет если (! isset($appsConfig[$_REQUEST['auth']['application_token']])) { вернуть false; } // сброс переменных приложения unset($appsConfig[$_REQUEST['auth']['application_token']]); // сохранить параметры saveParams($appsConfig);  } // событие получения "Установка приложения" еще { if ($_REQUEST['event'] == 'ONAPPINSTALL') { // обработчик событий $handlerBackUrl = ($_SERVER['SERVER_PORT'] == 443 ? 'https': 'http'). "://". $_SERVER['SERVER_NAME'] . (in_array($_SERVER['SERVER_PORT'],
               массив (80, 443)? '' : ':' . $_SERVER['SERVER_PORT']). $_SERVER['SCRIPT_NAME']; // Если ваше приложение поддерживает различные локализации
            // используйте $_REQUEST['data']['LANGUAGE_ID'] для загрузки правильной локализации
            // зарегистрировать нового бота
            $result = restCommand('imbot.register', array( 'CODE' => 'ReportBot', // уникальный идентификатор строкового бота приложения (обязательно)
               'TYPE' => 'B', // Тип бота: B - робот с немедленным ответом; H - человекоподобный бот с задержкой ответа от 2 до 10 секунд
               'EVENT_MESSAGE_ADD' => $handlerBackUrl, // новое сообщение от обработчика событий пользователя (обязательно)
               'EVENT_WELCOME_MESSAGE' => $handlerBackUrl, // обработчик событий "bot invited" (обязательно)
               'EVENT_BOT_DELETE' => $handlerBackUrl, // обработчик событий "пользователь удалил бота" (обязательно)
               'PROPERTIES' => array( // Персональные данные чат-бота (обязательно)
                  'NAME' => 'Reportoo', // Имя бота (требуется ИМЯ или ФАМИЛИЯ)
                  'LAST_NAME' => '', // Имя бота (требуется ИМЯ или ФАМИЛИЯ)
                  'COLOR' => 'AQUA', // Цвет бота для мобильного приложения: RED, GREEN, MINT, LIGHT_BLUE, DARK_BLUE, PURPLE, AQUA, PINK, LIME, BROWN, AZURE, KHAKI, SAND, MARENGO, GRAY, GRAPHITE
                  'EMAIL' => 'no@mail.com', // электронная почта бота
                  'PERSONAL_BIRTHDAY' => '2016-03-23', // день рождения, YYYY-mm-dd
                  'WORK_POSITION' => 'Я здесь, чтобы рассказать вам о ваших задачах', // Позиция - используется в качестве описания бота 'PERSONAL_WWW' => '', // ссылка на сайт 'PERSONAL_GENDER' => 'M', // Пол бота, (M) мужской или (F) женский или пустой, если не требуется :Программа, а также проведенная им добыта, а также, а такжедобдобдобдобдобдобдобдобдобдобдобдобдоб, аим, а, а, а, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до, до,
                  // Аватар бота - base64), ), $_REQUEST["auth"]); // сохранить параметры
            $appsConfig[$_REQUEST['auth']['application_token']] = массив( 'BOT_ID' => $result['result'], 'LANGUAGE_ID' => $_REQUEST['data']['LANGUAGE_ID'], ); saveParams($appsConfig); // запись журнала отладки
            // writeToLog($result, 'ReportBot register');} } } }/** * Сохраните конфигурацию приложения. * * @param $params * * @return bool */
функция saveParams($params) {
   $config = "<? php\n"; $config .= "\$appsConfig = " . var_export($params, true) . ";\n"; $config. = "? >"; $configFileName = '/config_' . trim(str_replace('.', '_', $_REQUEST['auth']['domain'])) . '.php'; file_put_contents(__DIR__ . $configFileName, $config); вернуть true; }/** * Отправьте запрос на отдых в Битрикс24. * * @param $method - Метод отдыха, например: методы * @param array $params - Метод params, например: array() * @param array $auth - Авторизация данных, например: array('domain' => 'https://test.bitrix24.com', 'access_token' => '7inpwszbuu8vnwr5jmabqa467rqur7u6') * * @return смешанный */
функция restCommand($method, array $params = array(), array $auth = array()) {
   $queryUrl = 'https://' . $auth['domain'] . '/rest/' . $method; $queryData = http_build_query(array_merge($params, array('auth' => $auth['access_token']))); // writeToLog(array('URL' => $queryUrl, 'PARAMS' => array_merge($params, array("auth" => $auth["access_token"]))), 'ReportBot send data');
   $curl = curl_init(); curl_setopt_array($curl, массив( CURLOPT_POST => 1, CURLOPT_HEADER => 0, CURLOPT_RETURNTRANSFER => 1, CURLOPT_URL => $queryUrl, CURLOPT_POSTFIELDS => $queryData, )); $result = curl_exec($curl); curl_close($curl); $result = json_decode($result, 1); возврат $result; }/** * Запишите данные в файл журнала. * * @param смешанные $data * @param string $title * * @return bool */
функция writeToLog($data, $title = '') {
   $log = "\n------------------------\n"; $log .= date("Y.m.d G:i:s") . "\n"; $log .= (strlen($title) > 0 ? $title: 'DEBUG') . "\n"; $log .= print_r($data, 1); $log .= "\n-------------------------\n"; file_put_contents(__DIR__ . '/imbot.log', $log, FILE_APPEND); вернуть true; }/** * Команда получена, создайте отчет * * @param string $текстовое сообщение, отправленное пользователем * @param int $ идентификатор пользователя * * @return массив */
функция getAnswer($command = '', $user) {

   переключатель (strtolower($command)) { случай "что горячего": $arResult = b24BadTasks($user); перерыв; по умолчанию: $arResult = массив ( 'title' => 'I'm stuck', 'report' => 'Извините, чего вы хотели? Я тебя не слышу!", ); }  возврат $arResult; }  функция b24BadTasks ($пользователь) { $tasks = restCommand('task.item.list', массив ( 'ORDER' => array('DEADLINE' => 'desc'), 'FILTER' => array('RESPONSIBLE_ID' => $user, '<DEADLINE' => 'Y-m-d'), 'PARAMS' => array(), 'SELECT' => array() ), $_REQUEST["auth"]);  if (count($tasks['result']) > 0) { $arTasks = array(); foreach ($tasks['result'] как $id => $arTask) { $arTasks[] = массив ( 'LINK' => массив ( 'NAME' => $arTask['TITLE'], 'LINK' => 'https://'. $_REQUEST['auth']['domain'].'/company/personal/user/'.$arTask['RESPONSIBLE_ID'].'/tasks/task/view/'.$arTask['ID'].' /') ); $arTasks[] = массив ( 'DELIMITER' => массив ( 'РАЗМЕР' => 400, 'ЦВЕТ' => '#c6c6c6') ); } $arReport = массив ( 'title' => 'О да, у нас проблемы. Реатакляй это как можно скорее: 'report' => '', 'attach' => $arTasks ); } еще { $arReport = массив ( 'title' => 'You're awesome!', 'report' => 'Вы не веселы, нет просроченных задач. Просто шучу, продолжай в том же духе!", ); } вернуть $arReport; }
